### ISSUE TITLE
Add specifications to docs

### ISSUE THREAD

**Issue by vembacher-unbasical** [unbasical/doras#17]
## Description

At the moment the specification of doras is spread across a number of different issues. This should be moved to a markdown file that summarizes the results of the discussions in #9, #10 and #12.

## Todos:

- [x] Add OpenAPI spec (#7)
- [x] Add storage layout spec
- [x] Add delta creation spec
   - [x] Calculation of a delta artifact (single artifact)
   - [x] Creation workflow (distributed system)
