### ISSUE TITLE
Add openapi.yaml

### ISSUE THREAD

**Issue by vembacher-unbasical** [unbasical/doras#7]
Depends on #9 

## Todos

- [x] Remove old swagger docs server and autogenerated files.
- [x] Write openapi.yaml file
- [ ] Serve new docs (optional)
