### ISSUE TITLE
Design initial cloud API

### ISSUE THREAD

**Issue by vembacher-unbasical** [unbasical/doras#9]
## Context

Doras will follow the following general architecture:
- Artifacts and deltas are stored in OCI registries.
- Artifacts are managed externally, this reduces the complexity and we can re-use existing tooling.
- Deltas are managed by Doras.

![Image](https://github.com/user-attachments/assets/262bed06-c58d-499c-877d-639865d73cb9)

## Goals

- Keep Doras server focused on building and serving deltas.
- Make API misuse difficult, to avoid bricked devices.

### Query Parameters: 
- mandatory:
  - `from_digest`
  - one of: 
    - `to_digest`
    - `to_tag`
- optional:    
  - `accepted_algorithm`

#### Delta is getting generated and will be ready soon

Status: 202 Accepted

Response Body: None

#### Delta is ready to pull (meets the requirements of the request)

Status: 200 OK

Response Body:
```json
{"deltaImage": "registry.example.org/deltas/foo@sha256-abc....ef"}
```

#### Missing Query Parameters

Status: 400 Bad Request.

Response Body:

```json
{
  "type": "https://github.com/unbasical/doras-server/internal/pkg/api/openapi-spec/cloud-api.md",
  "title": "example title",
  "status": 400,
  "detail": "missing query parameter `from_digest`",
  "instance": "https://github.com/unbasical/doras-server/internal/pkg/api/openapi-spec/cloud-api.md#missing-parameter"
}
```

#### Source or target digest/image are not available

Status: 404 Not Found

Response Body:

```json
{
  "type": "https://github.com/unbasical/doras-server/internal/pkg/api/openapi-spec/cloud-api.md",
  "title": "failed to resolve image(s)",
  "status": 404,
  "detail": "could not resolve from_digest=registry.example.org/foo@sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "instance": "https://github.com/unbasical/doras-server/internal/pkg/api/openapi-spec/cloud-api.md#failed-to-resolve-image"
}
```

#### Requested delta algorithm is not supported

Status: 406 Not Acceptable

Response Body:

```json
{
  "type": "https://github.com/unbasical/doras-server/internal/pkg/api/openapi-spec/cloud-api.md",
  "title": "Unsupported delta algorithm.",
  "status": 406,
  "detail": "Algorithm `foodiff` is not supported.",
  "instance": "https://github.com/unbasical/doras-server/internal/pkg/api/openapi-spec/cloud-api.md#unsupported-algorithm"
}
```

#### Pitfalls

- Handling parallel requests for identical deltas from many devices.

### Other Possible Endpoints

- Endpoint to load blobs via HTTP from the Doras server to support devices who cannot use OCI clients for whatever reason.
- Endpoints to manage artifacts (CRUD)
  - Might be interesting to support use cases where users/systems using Doras do not work with OCI registries.
  - Urgency: not very urgent, artifacts can initially be managed with OCI tooling.
  - Downside: introduces a lot of complexity to reach feature parity with OCI tooling.
- Endpoints to manage deltas.
  - E.g. to delete deltas.
  - How urgent is this? Since the deltas are stored in an OCI registry and can also be managed with existing tooling.

## Todos:

- [ ] Finalize API
  - [x] finalize accepted_algorithm(s) parameter
  - [ ] add mechanism to communicate that a delta is not possible and clients need to download a fresh artifact
- [x] Create OpenAPI specification.
